# 端口号
server:
  port: 82

spring:
  #热部署
  devtools:
    restart:
      enabled: true

# Dubbo
dubbo:
  # 注册中心
  application:
    id: dubbo-provider-demo
    name: dubbo-provider-demo
  # 注册中心
  registry:
    id: lcn-rpc-provider
    protocol: zookeeper
    address: localhost
    port: 2181
  # 实现类路径
  scan:
    base-packages: com.can.provider.impl
  # 协议
  protocol:
    id: dubbo
    name: dubbo
    port: 20880


